language: node_js
node_js: 14
before_script:
  - yarn install
jobs:
  include:
  - stage: test
    script:
    - yarn build
    - yarn test
  - stage: e2e
    script:
    - yarn e2e:run

# safelist
branches:
  only:
  - master
